### ISSUE TITLE
`OrdinalLogisticModel` does not work when `predictor.forward` accepts multiple arguments

### ISSUE THREAD

**Issue by sumanthratna** [EthanRosenthal/spacecutter#12]
https://github.com/EthanRosenthal/spacecutter/blob/37a6f7367905b50e7886dc1ef2bfe1d63220347a/spacecutter/models.py#L81-L82

solution: instead of accepting `X`, accept `*args` and `**kwargs`

happy to submit a PR to fix this

**Comment by EthanRosenthal** [comment]
Sure, feel free to submit a PR!
