### ISSUE TITLE
some question about the code

### ISSUE THREAD

**Issue by Shu-HowTing** [EthanRosenthal/spacecutter#15]
```py
class OrdinalLogisticModel(nn.Module):
"""
 Parameters
    ----------
    predictor : nn.Module
        When called, must return a torch.FloatTensor with shape [batch_size, 1]
"""
```
hello , thank u  for sharing! I have a question here. why  `return a torch.FloatTensor with shape [batch_size, 1]`. Shouldn't it be `return a torch.FloatTensor with shape [batch_size, num_class - 1]`?

**Comment by Shu-HowTing** [comment]
oh，sorry，maybe you are right, no matter what the value of $num\\_class$, the predictor output the logit value of the sample. it should be a scalar. just like the linear regression!

**Comment by EthanRosenthal** [comment]
Yup, exactly!
