### ISSUE TITLE
Using TensorRT

### ISSUE THREAD

**Issue by Arunavameister** [EthanRosenthal/spacecutter#6]
Hello,
Firstly, thanks a lot for making this useful repo public.
My question is regarding the conversion of an OrdinalLogisticModel() wrapped model to its tensorRT equivalent.
I am unable to do it and I think it has something to do with the LogisticCumulativeLink at the end of the wrapper class.
Have you personally tried converting the model to tensorrt for faster inference?
If yes, would you be kind enough to let me know.
Thank you

**Comment by EthanRosenthal** [comment]
Unfortunately, I have not tried to convert anything here to TensorRT. In fact, I didn't even know what TensorRT was until you opened this issue! Sorry I can't be of more help. If you're able to fix the problem, then I would welcome a PR to fix it here.

**Comment by Arunavameister** [comment]
Thank you for your reply. Apparently, custom models cannot be yet be converted to TensoRT compatible models and we just have to wait until it is supported.
In any case, thank you again for the repo. 
I will close the issue
