### ISSUE TITLE
Skorch supports torch 0.4.1 no more.

### ISSUE THREAD

**Issue by YpLarryWang** [EthanRosenthal/spacecutter#9]
Hi! Thanks for your work, I think it's useful and inspiring, however, Skorch may support torch 0.4.1 no more. When I try to run 'from Skorch.callbacks import Callback, ProgressBar', I met 'ImportWarning: Skorch depends on a newer version of PyTorch (at least 1.1.0, not 0.4.1). Visit https://pytorch.org for installation details', may be spacecutter should upgrade torch version? Thanks a lot!

**Comment by EthanRosenthal** [comment]
Oh yeah, there's no reason spacecutter should be hardpinned to a specific pytorch version. I'll submit a fix
